'use strict';
const topicIds=['children','resus','hospital','arrival','payment','alcohol','drugs'];
const statusText={waiting:'Ожидает ответа',clarify:'Нужно уточнить',approved:'Согласовано'};
const storageKey='rnch-client-review-v1';
let answers={};
try{answers=JSON.parse(localStorage.getItem(storageKey)||'{}')||{};}catch(e){document.getElementById('storage-note').textContent='Сохранение в браузере недоступно. Скачайте ответы перед закрытием страницы.';}
function updateProgress(){const approved=topicIds.filter(id=>answers[id]?.status==='approved').length;document.getElementById('progress').textContent=`Согласовано: ${approved} из ${topicIds.length}`;}
function renderStatus(id){const el=document.querySelector(`[data-status-label="${id}"]`),status=answers[id]?.status||'waiting';el.textContent=statusText[status]||statusText.waiting;el.className='status '+status;updateProgress();}
function persist(id){const answer=document.querySelector(`[data-answer="${id}"]`).value,status=document.querySelector(`[data-status="${id}"]`).value;answers[id]={answer,status};try{localStorage.setItem(storageKey,JSON.stringify(answers));document.querySelector(`[data-saved="${id}"]`).textContent='Сохранено в этом браузере';}catch(e){document.querySelector(`[data-saved="${id}"]`).textContent='Скачайте ответы для сохранения';}renderStatus(id);}
for(const id of topicIds){const textarea=document.querySelector(`[data-answer="${id}"]`),select=document.querySelector(`[data-status="${id}"]`);textarea.value=typeof answers[id]?.answer==='string'?answers[id].answer:'';select.value=statusText[answers[id]?.status]?answers[id].status:'waiting';textarea.addEventListener('input',()=>persist(id));select.addEventListener('change',()=>persist(id));renderStatus(id);}
document.getElementById('export').addEventListener('click',()=>{let lines=['РНЦХ / Med.ru — вопросы на согласование','Дата выгрузки: '+new Date().toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+' (Москва)',''];for(const id of topicIds){const card=document.getElementById(id);lines.push(card.querySelector('h2').textContent,'Статус: '+statusText[answers[id]?.status||'waiting'],'Вопросы:',...Array.from(card.querySelectorAll('ol li'),(li,i)=>`${i+1}. ${li.textContent}`),'Ответ: '+(answers[id]?.answer||'Ответ не заполнен'),'');}const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='RNCH_согласование.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.getElementById('print').addEventListener('click',()=>{document.querySelectorAll('textarea').forEach(el=>{el.style.height='auto';el.style.height=(el.scrollHeight+12)+'px';});window.print();});
